-- ========================================================================
-- PickleBall4All - Supabase Database Schema
-- Project ID: seelycwozohgvrxayvvt
-- Run this in your Supabase SQL Editor (https://supabase.com/dashboard/project/seelycwozohgvrxayvvt/sql)
-- ========================================================================

-- 1. Create the 'bookings' table
create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  full_name text not null,
  phone_number text not null,
  email text,
  playing_level text,
  program_type text,
  timing_pref text,
  notes text,
  status text default 'pending' check (status in ('pending', 'confirmed', 'completed', 'cancelled'))
);

-- 2. Add comment for documentation
comment on table public.bookings is 'Coaching session inquiries and booking requests for PickleBall4All';

-- 3. Enable Row Level Security (RLS)
alter table public.bookings enable row level security;

-- 4. Policy: Allow anonymous and authenticated visitors to submit bookings
create policy "Allow anonymous booking submissions"
on public.bookings
for insert
to anon, authenticated
with check (true);

-- 5. Policy: Allow authenticated admin users (Coach Hari) to view all bookings
create policy "Allow authenticated admin reads"
on public.bookings
for select
to authenticated
using (true);

-- 6. Policy: Allow authenticated admin users to update booking status
create policy "Allow authenticated admin updates"
on public.bookings
for update
to authenticated
using (true)
with check (true);
